/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountBookingsRouteImport } from './routes/account/bookings'
import { Route as AccountItinerariesRouteImport } from './routes/account/itineraries'
import { Route as AccountOverviewRouteImport } from './routes/account/overview'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountReviewsRouteImport } from './routes/account/reviews'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminDestinationsRouteImport } from './routes/admin/destinations'
import { Route as AdminFlightsRouteImport } from './routes/admin/flights'
import { Route as AdminHotelsRouteImport } from './routes/admin/hotels'
import { Route as AdminInboxRouteImport } from './routes/admin/inbox'
import { Route as AdminOverviewRouteImport } from './routes/admin/overview'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as CheckoutConfirmationRouteImport } from './routes/checkout/confirmation'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as HotelsIdRouteImport } from './routes/hotels.$id'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as AccountItinerariesIdRouteImport } from './routes/account/itineraries.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountBookingsRoute = AccountBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountItinerariesRoute = AccountItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOverviewRoute = AccountOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReviewsRoute = AccountReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDestinationsRoute = AdminDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlightsRoute = AdminFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHotelsRoute = AdminHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CheckoutConfirmationRoute = CheckoutConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => CheckoutRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const HotelsIdRoute = HotelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HotelsRoute,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PackagesRoute,
} as any)
const AccountItinerariesIdRoute = AccountItinerariesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountItinerariesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/flights': typeof FlightsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRouteWithChildren
  '/register': typeof RegisterRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/itineraries': typeof AccountItinerariesRouteWithChildren
  '/account/overview': typeof AccountOverviewRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/flights': typeof AdminFlightsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/confirmation': typeof CheckoutConfirmationRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/hotels/$id': typeof HotelsIdRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/itineraries/$id': typeof AccountItinerariesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/flights': typeof FlightsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRouteWithChildren
  '/register': typeof RegisterRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/itineraries': typeof AccountItinerariesRouteWithChildren
  '/account/overview': typeof AccountOverviewRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/flights': typeof AdminFlightsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/confirmation': typeof CheckoutConfirmationRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/hotels/$id': typeof HotelsIdRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/itineraries/$id': typeof AccountItinerariesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/flights': typeof FlightsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRouteWithChildren
  '/register': typeof RegisterRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/itineraries': typeof AccountItinerariesRouteWithChildren
  '/account/overview': typeof AccountOverviewRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reviews': typeof AccountReviewsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/destinations': typeof AdminDestinationsRoute
  '/admin/flights': typeof AdminFlightsRoute
  '/admin/hotels': typeof AdminHotelsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/confirmation': typeof CheckoutConfirmationRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/hotels/$id': typeof HotelsIdRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/account/itineraries/$id': typeof AccountItinerariesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/destinations'
    | '/flights'
    | '/forgot-password'
    | '/gallery'
    | '/hotels'
    | '/login'
    | '/packages'
    | '/register'
    | '/account/bookings'
    | '/account/itineraries'
    | '/account/overview'
    | '/account/profile'
    | '/account/reviews'
    | '/admin/bookings'
    | '/admin/destinations'
    | '/admin/flights'
    | '/admin/hotels'
    | '/admin/inbox'
    | '/admin/overview'
    | '/admin/packages'
    | '/admin/reviews'
    | '/admin/users'
    | '/checkout/confirmation'
    | '/destinations/$slug'
    | '/hotels/$id'
    | '/packages/$slug'
    | '/account/'
    | '/admin/'
    | '/account/itineraries/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/contact'
    | '/destinations'
    | '/flights'
    | '/forgot-password'
    | '/gallery'
    | '/hotels'
    | '/login'
    | '/packages'
    | '/register'
    | '/account/bookings'
    | '/account/itineraries'
    | '/account/overview'
    | '/account/profile'
    | '/account/reviews'
    | '/admin/bookings'
    | '/admin/destinations'
    | '/admin/flights'
    | '/admin/hotels'
    | '/admin/inbox'
    | '/admin/overview'
    | '/admin/packages'
    | '/admin/reviews'
    | '/admin/users'
    | '/checkout/confirmation'
    | '/destinations/$slug'
    | '/hotels/$id'
    | '/packages/$slug'
    | '/account'
    | '/admin'
    | '/account/itineraries/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/destinations'
    | '/flights'
    | '/forgot-password'
    | '/gallery'
    | '/hotels'
    | '/login'
    | '/packages'
    | '/register'
    | '/account/bookings'
    | '/account/itineraries'
    | '/account/overview'
    | '/account/profile'
    | '/account/reviews'
    | '/admin/bookings'
    | '/admin/destinations'
    | '/admin/flights'
    | '/admin/hotels'
    | '/admin/inbox'
    | '/admin/overview'
    | '/admin/packages'
    | '/admin/reviews'
    | '/admin/users'
    | '/checkout/confirmation'
    | '/destinations/$slug'
    | '/hotels/$id'
    | '/packages/$slug'
    | '/account/'
    | '/admin/'
    | '/account/itineraries/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  FlightsRoute: typeof FlightsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  HotelsRoute: typeof HotelsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/bookings': {
      id: '/account/bookings'
      path: '/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AccountBookingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/itineraries': {
      id: '/account/itineraries'
      path: '/itineraries'
      fullPath: '/account/itineraries'
      preLoaderRoute: typeof AccountItinerariesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/overview': {
      id: '/account/overview'
      path: '/overview'
      fullPath: '/account/overview'
      preLoaderRoute: typeof AccountOverviewRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reviews': {
      id: '/account/reviews'
      path: '/reviews'
      fullPath: '/account/reviews'
      preLoaderRoute: typeof AccountReviewsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/destinations': {
      id: '/admin/destinations'
      path: '/destinations'
      fullPath: '/admin/destinations'
      preLoaderRoute: typeof AdminDestinationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flights': {
      id: '/admin/flights'
      path: '/flights'
      fullPath: '/admin/flights'
      preLoaderRoute: typeof AdminFlightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hotels': {
      id: '/admin/hotels'
      path: '/hotels'
      fullPath: '/admin/hotels'
      preLoaderRoute: typeof AdminHotelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/checkout/confirmation': {
      id: '/checkout/confirmation'
      path: '/confirmation'
      fullPath: '/checkout/confirmation'
      preLoaderRoute: typeof CheckoutConfirmationRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/hotels/$id': {
      id: '/hotels/$id'
      path: '/$id'
      fullPath: '/hotels/$id'
      preLoaderRoute: typeof HotelsIdRouteImport
      parentRoute: typeof HotelsRoute
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof PackagesRoute
    }
    '/account/itineraries/$id': {
      id: '/account/itineraries/$id'
      path: '/$id'
      fullPath: '/account/itineraries/$id'
      preLoaderRoute: typeof AccountItinerariesIdRouteImport
      parentRoute: typeof AccountItinerariesRoute
    }
  }
}

interface AccountItinerariesRouteChildren {
  AccountItinerariesIdRoute: typeof AccountItinerariesIdRoute
}

const AccountItinerariesRouteChildren: AccountItinerariesRouteChildren = {
  AccountItinerariesIdRoute: AccountItinerariesIdRoute,
}

const AccountItinerariesRouteWithChildren =
  AccountItinerariesRoute._addFileChildren(AccountItinerariesRouteChildren)

interface AccountRouteChildren {
  AccountBookingsRoute: typeof AccountBookingsRoute
  AccountItinerariesRoute: typeof AccountItinerariesRouteWithChildren
  AccountOverviewRoute: typeof AccountOverviewRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountReviewsRoute: typeof AccountReviewsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountBookingsRoute: AccountBookingsRoute,
  AccountItinerariesRoute: AccountItinerariesRouteWithChildren,
  AccountOverviewRoute: AccountOverviewRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountReviewsRoute: AccountReviewsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDestinationsRoute: typeof AdminDestinationsRoute
  AdminFlightsRoute: typeof AdminFlightsRoute
  AdminHotelsRoute: typeof AdminHotelsRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDestinationsRoute: AdminDestinationsRoute,
  AdminFlightsRoute: AdminFlightsRoute,
  AdminHotelsRoute: AdminHotelsRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutConfirmationRoute: typeof CheckoutConfirmationRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutConfirmationRoute: CheckoutConfirmationRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface HotelsRouteChildren {
  HotelsIdRoute: typeof HotelsIdRoute
}

const HotelsRouteChildren: HotelsRouteChildren = {
  HotelsIdRoute: HotelsIdRoute,
}

const HotelsRouteWithChildren =
  HotelsRoute._addFileChildren(HotelsRouteChildren)

interface PackagesRouteChildren {
  PackagesSlugRoute: typeof PackagesSlugRoute
}

const PackagesRouteChildren: PackagesRouteChildren = {
  PackagesSlugRoute: PackagesSlugRoute,
}

const PackagesRouteWithChildren = PackagesRoute._addFileChildren(
  PackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  FlightsRoute: FlightsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  HotelsRoute: HotelsRouteWithChildren,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
